const Fileimages = [
  // ================= GROCERIES =================
  {
    id: "14",
    name: "Onion",
    image: "https://ik.imagekit.io/w0yidd7r6/onion?updatedAt=1768837202629",
    new_price: 40.0,
    old_price: 60,
    category: "grocery",
    off: "33% off",
    rating: "4.2",
    expiry: "5 days",
    weight: "1kg",
    brand: "FreshFarm",
    tags: ["grocery", "vegetable"],
  },
  {
    id: "9",
    name: "Nuts",
    image: "https://ik.imagekit.io/w0yidd7r6/nuts-kaju",
    new_price: 250.0,
    old_price: 300,
    category: "grocery",
    off: "17% off",
    rating: "4.7",
    expiry: "6 months",
    weight: "500g",
    brand: "NutriChoice",
    tags: ["grocery", "kaju", "snack"],
  },
    {
    id: "22",
    name: "Striped Peplum Hem Top",
    category: "fashion",
    image: "https://ik.imagekit.io/w0yidd7r6/product_17.png",
    new_price: 999,
    old_price: 1599,
    rating: "4.3",
    brand: "ONLY",
    size: ["M", "L", "XL"],
    color: ["Green", "White"],
    material: "Cotton",
    description: "Comfortable striped peplum top with breathable cotton fabric.",
    tags: ["fashion", "women", "top"],
  },
  {
    id: "17",
    name: "Dark Chocolate",
    image: "https://ik.imagekit.io/w0yidd7r6/darkchacolate?updatedAt=1768837199212",
    new_price: 120.0,
    old_price: 180,
    category: "grocery",
    off: "33% off",
    rating: "4.8",
    expiry: "12 months",
    weight: "100g",
    brand: "Cadbury",
    tags: ["grocery", "chocolate", "snack"],
  },
  {
    id: "18",
    name: "Ginger",
    image: "https://ik.imagekit.io/w0yidd7r6/ginger?updatedAt=1768837202682",
    new_price: 35.0,
    old_price: 50,
    category: "grocery",
    off: "30% off",
    rating: "4.4",
    expiry: "7 days",
    weight: "500g",
    brand: "FreshFarm",
    tags: ["grocery", "spice", "ginger"],
  },

  // ================= ELECTRONICS =================
  {
    id: "1",
    product: "Mobile",
    image: "https://ik.imagekit.io/w0yidd7r6/iphone%2013%20pro.png",
    company: "Iphone",
    name: "iPhone 13",
    new_price: 10999.0,
    old_price: 200000,
    category: "electronics",
    off: "40% off",
    ram: "8GB",
    rom: "256GB",
    battery: "5000mah",
    description:
      "The latest iPhone model with advanced camera capabilities and powerful performance.",
    rating: "4.5",
    tags: ["electronics", "mobile", "phone", "iphone"],
  },
  {
    id: "3",
    product: "Mobile",
    image: "https://ik.imagekit.io/w0yidd7r6/lava.jpg",
    company: "Lava",
    name: "Lava",
    new_price: 29999,
    old_price: 40000,
    category: "electronics",
    off: "30% off",
    ram: "16GB",
    rom: "256GB",
    battery: "5500mah",
    rating: "4.7",
    tags: ["electronics", "mobile", "phone", "lava"],
  },
  {
    id: "6",
    product: "Laptop",
    image: "https://ik.imagekit.io/w0yidd7r6/MSI.jpg",
    company: "MSI",
    name: "MSI Laptop",
    new_price: 49999,
    old_price: 200000,
    category: "electronics",
    off: "45% off",
    rating: "3.6",
    processor: "Snapdragon",
    battery: "25000",
    ram: "8GB",
    rom: "256GB",
    battery: "5000mah",
    tags: ["electronics", "laptop"],
  },
  {
    id: "7",
    product: "Tablet",
    image: "https://ik.imagekit.io/w0yidd7r6/t1.png",
    company: "Apple",
    name: "iPad",
    new_price: 749.0,
    old_price: 200000,
    category: "electronics",
    off: "65% off",
    rating: "4.5",
    battery: "2500",
    tags: ["electronics", "ipad", "tablet"],
  },
  {
    id: "8",
    product: "Power Bank",
    image: "https://ik.imagekit.io/w0yidd7r6/pr10.png",
    company: "Samsung",
    name: "Power Bank",
    new_price: 599.99,
    old_price: 200000,
    category: "electronics",
    off: "20% off",
    rating: "4.9",
    battery: "50000",
    tags: ["electronics", "powerbank"],
  },
  {
    id: "12",
    product: "Laptop",
    image: "https://ik.imagekit.io/w0yidd7r6/HP%20i5.jpg",
    company: "HP",
    name: "HP i3",
    new_price: 37999.99,
    old_price: 200000,
    category: "electronics",
    off: "15% off",
    rating: "5.0",
     ram: "8GB",
    rom: "256GB",
    battery: "5000mah",
    tags: ["electronics", "laptop"],
  },
  {
    id: "13",
    product: "Mobile",
    image: "https://ik.imagekit.io/w0yidd7r6/VIVO%20Y%20100.jpg",
    company: "Vivo",
    name: "Vivo Y100",
    new_price: 37999.99,
    old_price: 200000,
    category: "electronics",
    off: "35% off",
    ram: "8GB",
    rom: "256GB",
    battery: "5000mah",
    rating: "4.7",
    tags: ["electronics", "mobile", "phone"],
  },
    {
    id: "2",
    name: "Fortune Oil",
    image: "https://ik.imagekit.io/w0yidd7r6/oil",
    new_price: 75.0,
    old_price: 120,
    category: "grocery",
    off: "37% off",
    rating: "4.5",
    expiry: "12 months",
    weight: "1L",
    brand: "Fortune",
    tags: ["grocery", "oil", "cooking"],
  },
  {
    id: "4",
    product: "Smart Watch",
    image: "https://ik.imagekit.io/w0yidd7r6/Tissot%20smartwatch.jpg",
    company: "Tissot",
    name: "SmartWatch",
    new_price: 899.0,
    old_price: 200000,
    category: "electronics",
    off: "10% off",
    rating: "3.9",
    tags: ["electronics", "watch", "smartwatch"],
  },
  {
    id: "15",
    product: "Mobile",
    image: "https://ik.imagekit.io/w0yidd7r6/iqoo7pro.jpg",
    company: "IQOO",
    name: "IQOO",
    new_price: 40000.99,
    old_price: 200000,
    category: "electronics",
    off: "39% off",
    ram: "6GB",
    rom: "256GB",
    battery: "5500mah",
    rating: "4.2",
    tags: ["electronics", "mobile", "phone"],
  },
  {
    id: "16",
    name: "Mouse",
    image: "https://ik.imagekit.io/w0yidd7r6/pr11.png",
    company: "Logitech",
    model: "Gaming Mouse",
    new_price: 17999,
    old_price: 30000,
    category: "electronics",
    off: "65% off",
    description: "High precision gaming mouse.",
    tags: ["electronics", "mouse", "accessory"],
  },
  {
    id: "19",
    product: "Mobile",
    image: "https://ik.imagekit.io/w0yidd7r6/GT%20NEO%203.jpg",
    company: "Realme",
    name: "Realme GT",
    new_price: 379.99,
    old_price: 200000,
    category: "electronics",
    off: "45% off",
    ram: "16GB",
    rom: "256GB",
    battery: "5000mah",
    rating: "4.8",
    tags: ["electronics", "mobile", "phone", "realme"],
  },
  {
    id: "10",
    product: "Refrigerator",
    image: "https://ik.imagekit.io/w0yidd7r6/pr4.png",
    company: "LG",
    name: "Refrigerator",
    new_price: 8999.5,
    old_price: 200000,
    category: "electronics",
    off: "60% off",
    rating: "4.5",
    tags: ["electronics", "fridge", "refrigerator"],
  },
  {
    id: "5",
    product: "Headset",
    image: "https://ik.imagekit.io/w0yidd7r6/h1.png",
    company: "Boat",
    name: "Headset",
    new_price: 999.5,
    old_price: 200000,
    category: "electronics",
    off: "50% off",
    rating: "4.5",
    tags: ["electronics", "headset", "audio"],
  },

  // ================= FASHION =================
  {
    id: "20",
    name: "Striped Flutter Sleeve Peplum Top",
    category: "fashion",
    image: "https://ik.imagekit.io/w0yidd7r6/product_15.png",
    new_price: 1299,
    old_price: 1999,
    rating: "4.4",
    off: "33% off",
    brand: "ZARA",
    size: ["S", "M", "L", "XL"],
    color: ["Blue", "White"],
    material: "Cotton Blend",
    description:
      "Trendy striped peplum top with flutter sleeves and overlap collar. Ideal for casual and office wear.",
    tags: ["fashion", "women", "top"],
  },
  {
    id: "21",
    name: "Overlap Collar Peplum Blouse",
    category: "fashion",
    image: "https://ik.imagekit.io/w0yidd7r6/product_16.png",
    new_price: 1499,
    old_price: 2299,
    rating: "4.5",
    brand: "H&M",
    off: "33% off",
    size: ["S", "M", "L"],
    color: ["Pink", "White"],
    material: "Poly Crepe",
    description: "Elegant peplum blouse with soft fabric and modern overlap collar.",
    tags: ["fashion", "women", "blouse"],
  },

  {
    id: "23",
    name: "Solid Peplum Party Top",
    category: "fashion",
    image: "https://ik.imagekit.io/w0yidd7r6/product_31.png",
    new_price: 1799,
    old_price: 2799,
    rating: "4.6",
    brand: "VERO MODA",
    size: ["S", "M", "L"],
    color: ["Yellow"],
    material: "Rayon",
    description: "Premium solid peplum top perfect for parties and evening wear.",
    off: "33% off",
    tags: ["fashion", "women", "party"],
  },
  {
    id: "24",
    name: "Floral Printed Peplum Top",
    category: "fashion",
    image: "https://ik.imagekit.io/w0yidd7r6/product_24.png",
    new_price: 1199,
    old_price: 1899,
    rating: "4.2",
    brand: "BIBA",
    size: ["S", "M", "L", "XL"],
    color: ["Red", "White"],
    material: "Cotton",
    description: "Floral printed peplum top with lightweight fabric for daily wear.",
    tags: ["fashion", "women", "casual"],
  },
  {
    id: "25",
    name: "Printed Casual Peplum Top",
    category: "fashion",
    image: "https://ik.imagekit.io/w0yidd7r6/product_21.png",
    new_price: 1099,
    old_price: 1699,
    rating: "4.1",
    brand: "MAX",
    size: ["S", "M", "L", "XL"],
    color: ["Maroon"],
    material: "Cotton Blend",
    description: "Stylish printed peplum top suitable for everyday casual looks.",
    tags: ["fashion", "women", "top"],
  },
    {
    id: "11",
    name: "ThumsUp",
    image: "https://ik.imagekit.io/w0yidd7r6/thumsup?updatedAt=1768837208740",
    new_price: 50.0,
    old_price: 75,
    category: "grocery",
    off: "33% off",
    rating: "4.3",
    expiry: "12 months",
    weight: "500ml",
    brand: "CocaCola",
    tags: ["grocery", "beverage"],
  },
  {
    id: "26",
    name: "Classic Black Peplum Top",
    category: "fashion",
    image: "https://ik.imagekit.io/w0yidd7r6/product_30.png",
    new_price: 1599,
    old_price: 2499,
    rating: "4.3",
    brand: "MANGO",
    size: ["M", "L"],
    color: ["Black"],
    material: "Polyester",
    description: "Classic black peplum top with elegant slim-fit design.",
    tags: ["fashion", "women", "top"],
  },
  {
    id: "27",
    name: "Elegant Navy Blue Peplum Wear",
    category: "fashion",
    image: "https://ik.imagekit.io/w0yidd7r6/product_24.png",
    new_price: 1699,
    old_price: 2599,
    rating: "4.4",
    brand: "FOREVER 21",
    size: ["S", "M", "L"],
    color: ["Navy Blue"],
    material: "Georgette",
    description: "Elegant peplum wear with smooth texture and modern fit.",
    tags: ["fashion", "women", "party"],
  },
  {
    id: "28",
    name: "Casual Cotton Peplum Blouse",
    category: "fashion",
    image: "https://ik.imagekit.io/w0yidd7r6/product_28.png",
    new_price: 999,
    old_price: 1499,
    rating: "4.0",
    brand: "FABINDIA",
    size: ["M", "L", "XL"],
    color: ["Cream"],
    material: "Cotton",
    description: "Soft cotton peplum blouse with comfortable everyday fit.",
    tags: ["fashion", "women", "casual"],
  },
  {
    id: "29",
    name: "Stylish White Peplum Top",
    category: "fashion",
    image: "https://ik.imagekit.io/w0yidd7r6/product_23.png",
    new_price: 1399,
    old_price: 2199,
    rating: "4.3",
    brand: "AND",
    size: ["S", "M", "L"],
    color: ["White"],
    material: "Cotton",
    description: "Minimal white peplum top with a modern stylish cut.",
    tags: ["fashion", "women", "top"],
  },
  {
    id: "31",
    name: "Casual Fashion Top",
    category: "fashion",
    image: "https://ik.imagekit.io/w0yidd7r6/product_19.png",
    new_price: 1199,
    old_price: 1799,
    rating: "4.1",
    off: "33% off",
    brand: "ONLY",
    size: ["S", "M", "L"],
    color: ["Pink"],
    material: "Poly Crepe",
    description: "Simple casual fashion top suitable for everyday styling.",
    tags: ["fashion", "women"],
  },
  {
    id: "32",
    name: "Men Green Slim Fit Bomber Jacket",
    category: "fashion",
    image: "https://ik.imagekit.io/w0yidd7r6/product_18.png",
    new_price: 2999,
    old_price: 4999,
    rating: "4.6",
    brand: "ROADSTER",
    size: ["M", "L", "XL"],
    color: ["Green"],
    material: "Polyester",
    description: "Stylish slim-fit bomber jacket with zip closure for winter wear.",
    tags: ["fashion", "men", "jacket"],
  },

];

module.exports = Fileimages;

